version: "3.8"

name: xplg-graal-cluster

networks:
  xplgnet:

volumes:
  xplg_data: {} # Named volume for shared persistent storage (/home/data in all nodes)

# Reusable env map (so we can merge it into each service without overwriting)
x-xplg-common-env: &xplg-common-env
  ram: "-Xmx2g"
  # MUST be the full property string, not just a path
  sharedstorage: "xpolog.home.root.path=/home/data"

# Reusable common service bits
x-xplg-common: &xplg-common
  image: xplghub/images:xplg.RC-Graal-10206
  restart: unless-stopped
  networks: [xplgnet]
  environment: *xplg-common-env
  volumes:
    # Same named volume mounted at the same path in all nodes
    - xplg_data:/home/data

services:
  master:
    <<: *xplg-common
    container_name: xplg-master
    environment:
      <<: *xplg-common-env
      profile: "-Dxpolog.uid.structure=master"
      # Written verbatim into /opt/xplg-service/inception-conf.prop
      XPLG_INCEPTION_PARAMS: |
        xplg_inception_init_flow=master
        xplg_inceptions_post_init_flow_tasks=clusterExternalConf
    expose:
      - "30303"
      - "30443"
    volumes:
      # Persist MASTER logs to host
      - type: bind
        source: /home/xplg/xplg-cluster/cluster-logs/master/tomcat
        target: /opt/xplg-service/ServletContainer/logs
      - type: bind
        source: /home/xplg/xplg-cluster/cluster-logs/master/app
        target: /opt/xplg-service/log

  ui:
    <<: *xplg-common
    container_name: xplg-ui
    depends_on: [master]
    environment:
      <<: *xplg-common-env
      profile: "-Dxpolog.uid.structure=ui"
      XPLG_INCEPTION_PARAMS: |
        xplg_inception_init_flow=ui
        xplg_inceptions_post_init_flow_tasks=waitForFile
    # Publish UI ports to the host
    ports:
      - "30307:30303" # HTTP
      - "30447:30443" # HTTPS
    volumes:
      # Persist UI logs to host
      - type: bind
        source: /home/xplg/xplg-cluster/cluster-logs/ui/tomcat
        target: /opt/xplg-service/ServletContainer/logs
      - type: bind
        source: /home/xplg/xplg-cluster/cluster-logs/ui/app
        target: /opt/xplg-service/log
      # Also mount the whole cluster-logs tree for convenient browsing from the UI
      - type: bind
        source: /home/xplg/xplg-cluster/cluster-logs
        target: /home/xplg/xplg-cluster/cluster-logs

  processor:
    <<: *xplg-common
    container_name: xplg-processor
    depends_on: [master]
    environment:
      <<: *xplg-common-env
      profile: "-Dxpolog.uid.structure=processor"
      XPLG_INCEPTION_PARAMS: |
        xplg_inception_init_flow=processor
        xplg_inceptions_post_init_flow_tasks=waitForFile
    expose:
      - "30303"
      - "30443"
    volumes:
      # Persist PROCESSOR logs to host
      - type: bind
        source: /home/xplg/xplg-cluster/cluster-logs/processor/tomcat
        target: /opt/xplg-service/ServletContainer/logs
      - type: bind
        source: /home/xplg/xplg-cluster/cluster-logs/processor/app
        target: /opt/xplg-service/log
