version: "3.8"

name: xplg-graal-cluster
networks: { xplgnet: {} }

services:
  xplg-master:
    image: xplghub/images:xplg.RC-Graal-10206
    container_name: xplg-master
    restart: unless-stopped
    networks: [xplgnet]
    expose: ["30303", "30443"]
    environment:
      ram: "-Xmx2g"
      sharedstorage: "xpolog.home.root.path=/home/data"
      profile: "-Dxpolog.uid.structure=master"
      xplg_inception_init_flow: "master"
      xplg_inceptions_post_init_flow_tasks: "clusterExternalConf"
    volumes:
      # shared external config (dev-friendly bind)
      - type: bind
        source: ${HOST_DATA:-./data}
        target: /home/data
      # persist MASTER logs to host
      - ./cluster-logs/master/tomcat:/opt/xplg-service/ServletContainer/logs
      - ./cluster-logs/master/app:/opt/xplg-service/log

  xplg-ui:
    image: xplghub/images:xplg.RC-Graal-10206
    container_name: xplg-ui
    restart: unless-stopped
    networks: [xplgnet]
    ports:
      - "30307:30303" # HTTP
      - "30447:30443" # HTTPS
    depends_on: [xplg-master]
    environment:
      ram: "-Xmx2g"
      sharedstorage: "xpolog.home.root.path=/home/data"
      profile: "-Dxpolog.uid.structure=ui"
      xplg_inception_init_flow: "ui"
      xplg_inceptions_post_init_flow_tasks: "waitForFile"
    volumes:
      - type: bind
        source: ${HOST_DATA:-./data}
        target: /home/data
      - /home/xplg/xplg-cluster/cluster-logs:/home/xplg/xplg-cluster/cluster-logs
      # persist UI logs to host
      - ./cluster-logs/ui/tomcat:/opt/xplg-service/ServletContainer/logs
      - ./cluster-logs/ui/app:/opt/xplg-service/log

  xplg-processor:
    image: xplghub/images:xplg.RC-Graal-10206
    container_name: xplg-processor
    restart: unless-stopped
    networks: [xplgnet]
    expose: ["30303", "30443"]
    depends_on: [xplg-master]
    environment:
      ram: "-Xmx2g"
      sharedstorage: "xpolog.home.root.path=/home/data"
      profile: "-Dxpolog.uid.structure=processor"
      xplg_inception_init_flow: "processor"
      xplg_inceptions_post_init_flow_tasks: "waitForFile"
    volumes:
      - type: bind
        source: ${HOST_DATA:-./data}
        target: /home/data
      # persist PROCESSOR logs to host
      - ./cluster-logs/processor/tomcat:/opt/xplg-service/ServletContainer/logs
      - ./cluster-logs/processor/app:/opt/xplg-service/log
