version: "3.8"

name: xplg-graal-cluster

networks:
  xplgnet:

x-xplg-common: &xplg-common
  image: xplghub/images:xplg.RC-Graal-10206
  restart: unless-stopped
  networks: [xplgnet]
  # If you run on Apple Silicon locally, uncomment:
  # platform: linux/amd64
  environment:
    ram: "-Xmx2g"
    # IMPORTANT: this is the full property string, not just a path
    sharedstorage: "xpolog.home.root.path=/home/data"
  volumes:
    # Bind mount: host path -> container path
    - type: bind
      source: ${HOST_DATA}
      target: /home/data

services:
  master:
    <<: *xplg-common
    container_name: xplg-master
    environment:
      <<: *xplg-common.environment
      profile: "-Dxpolog.uid.structure=master"
      XPLG_INCEPTION_PARAMS: |
        xplg_inception_init_flow=master
        xplg_inceptions_post_init_flow_tasks=clusterExternalConf
    expose:
      - "30303"
      - "30443"

  ui:
    <<: *xplg-common
    container_name: xplg-ui
    environment:
      <<: *xplg-common.environment
      profile: "-Dxpolog.uid.structure=ui"
      XPLG_INCEPTION_PARAMS: |
        xplg_inception_init_flow=ui
        xplg_inceptions_post_init_flow_tasks=waitForFile
    # Publish only the UI
    ports:
      - "30307:30303"  # HTTP
      - "30447:30443"  # HTTPS
    depends_on:
      - master

  processor:
    <<: *xplg-common
    container_name: xplg-processor
    environment:
      <<: *xplg-common.environment
      profile: "-Dxpolog.uid.structure=processor"
      XPLG_INCEPTION_PARAMS: |
        xplg_inception_init_flow=processor
        xplg_inceptions_post_init_flow_tasks=waitForFile
    expose:
      - "30303"
      - "30443"
    depends_on:
      - master
