version: "3.8"

name: xplg-graal-cluster

networks:
  xplgnet:

volumes:
  xplg_data: {}   # Named volume for shared persistent storage

x-xplg-common: &xplg-common
  image: xplghub/images:xplg.RC-Graal-10206
  restart: unless-stopped
  networks: [xplgnet]
  # If you're on Apple Silicon locally, uncomment:
  # platform: linux/amd64
  environment:
    # JVM heap — tune to your VM memory
    ram: "-Xmx2g"
    # This MUST be the full property string, not just a path
    sharedstorage: "xpolog.home.root.path=/home/data"
  volumes:
    # Same named volume mounted at the same path in all nodes
    - xplg_data:/home/data

services:
  master:
    <<: *xplg-common
    container_name: xplg-master
    environment:
      <<: *xplg-common.environment
      profile: "-Dxpolog.uid.structure=master"
      # Written verbatim into /opt/xplg-service/inception-conf.prop
      XPLG_INCEPTION_PARAMS: |
        xplg_inception_init_flow=master
        xplg_inceptions_post_init_flow_tasks=clusterExternalConf
    # No host port publishing on purpose
    expose:
      - "30303"
      - "30443"

  ui:
    <<: *xplg-common
    container_name: xplg-ui
    environment:
      <<: *xplg-common.environment
      profile: "-Dxpolog.uid.structure=ui"
      XPLG_INCEPTION_PARAMS: |
        xplg_inception_init_flow=ui
        xplg_inceptions_post_init_flow_tasks=waitForFile
    # Publish UI ports to the host
    ports:
      - "30307:30303"  # HTTP
      - "30447:30443"  # HTTPS
    depends_on:
      - master

  processor:
    <<: *xplg-common
    container_name: xplg-processor
    environment:
      <<: *xplg-common.environment
      profile: "-Dxpolog.uid.structure=processor"
      XPLG_INCEPTION_PARAMS: |
        xplg_inception_init_flow=processor
        xplg_inceptions_post_init_flow_tasks=waitForFile
    expose:
      - "30303"
      - "30443"
    depends_on:
      - master
